# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Covender' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Covender
  pod 'Firebase/Analytics'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'FirebaseFirestoreSwift'

  target 'CovenderTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CovenderUITests' do
    # Pods for testing
  end

end
