//
//  RegisterUserViewController.swift
//  covender
//
//  Created Developers on 23/02/2019.
//  Copyright © 2019 Marc Tamarit. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import MaterialComponents.MaterialTextFields

class RegisterUserViewController: UIViewController, RegisterUserViewProtocol {

	var presenter: RegisterUserPresenterProtocol?
    @IBOutlet weak var nameTextField: MDCTextField!
    @IBOutlet weak var lastName: MDCTextField!
    @IBOutlet weak var password: MDCTextField!
    @IBOutlet weak var confirm: MDCTextField!
    @IBOutlet weak var email: MDCTextField!
    @IBOutlet weak var phone: MDCTextField!
    
    var nameTFController: MDCTextInputControllerUnderline?
    
	override func viewDidLoad() {
        super.viewDidLoad()
        
        nameTFController = MDCTextInputControllerUnderline(textInput: nameTextField)
        nameTFController?.underlineViewMode = .unlessEditing
        
    }

}
