//
//  RegisterUserInteractor.swift
//  covender
//
//  Created Developers on 23/02/2019.
//  Copyright © 2019 Marc Tamarit. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class RegisterUserInteractor: RegisterUserInteractorProtocol {

    weak var presenter: RegisterUserPresenterProtocol?
}
