//
//  RegisterUserProtocols.swift
//  covender
//
//  Created Developers on 23/02/2019.
//  Copyright © 2019 Marc Tamarit. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol RegisterUserWireframeProtocol: class {

}
//MARK: Presenter -
protocol RegisterUserPresenterProtocol: class {

}

//MARK: Interactor -
protocol RegisterUserInteractorProtocol: class {

  var presenter: RegisterUserPresenterProtocol?  { get set }
}

//MARK: View -
protocol RegisterUserViewProtocol: class {

  var presenter: RegisterUserPresenterProtocol?  { get set }
}
