//
//  RegisterUserPresenter.swift
//  covender
//
//  Created Developers on 23/02/2019.
//  Copyright © 2019 Marc Tamarit. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class RegisterUserPresenter: RegisterUserPresenterProtocol {

    weak private var view: RegisterUserViewProtocol?
    var interactor: RegisterUserInteractorProtocol?
    private let router: RegisterUserWireframeProtocol

    init(interface: RegisterUserViewProtocol, interactor: RegisterUserInteractorProtocol?, router: RegisterUserWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}
