//
//  RegisterUserRouter.swift
//  covender
//
//  Created Developers on 23/02/2019.
//  Copyright © 2019 Marc Tamarit. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class RegisterUserRouter: RegisterUserWireframeProtocol {
    
    weak var viewController: UIViewController?
    
    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = RegisterUserViewController(nibName: nil, bundle: nil)
        let interactor = RegisterUserInteractor()
        let router = RegisterUserRouter()
        let presenter = RegisterUserPresenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        
        return view
    }
}
